---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(ggrepel)
library(ArchR)
library(ggpubr)
library(BuenColors)
library(EnhancedVolcano)


mono.tf <- toupper(c("Atf5","Cebpb","Cebpa","Cebpd"))
neutro.tf <- toupper(c("Atf5","Cebpg","Cebpb","Cebpe"))
em.tf <- toupper(c("Gata1","Gata2","Gata3","Gata6"))
lym.tf <- toupper(c("Sfpi1","Mef2c","Bcl11a"))
pdc.tf <-toupper(c("Bcl11a","Sfpi1","Irf1"))
bem.tf <- toupper(c("Gata2","Gata1","Gata6"))

tf_markers <- list()
tf_markers[['Mono']] <- mono.tf
tf_markers[['Neutro']] <- neutro.tf
tf_markers[['Ery_Meg']] <- em.tf
tf_markers[['Lym']] <- lym.tf
tf_markers[['pDC_Ccr7DC']] <- pdc.tf
tf_markers[['Baso_Eos_Mast']] <- bem.tf

# plot_list <- list()
# for (i in seq_along(tf_markers)){
#   gene.expr <- read.csv(paste0("./220208/tf_activity/",names(tf_markers)[[i]],"_state_tfact_markers.csv"), row.names = 1)
#   gene.expr$colors_curr <- rep("grey",dim(gene.expr)[1])
#   gene.expr$tf <- unlist(lapply(rownames(gene.expr), function(x){str_split(x,"_")[[1]][1]}))
#   gene.expr$colors_curr[gene.expr$tf %in% tf_markers[[i]]] <- "#be1e2d"
#   gene.expr <- gene.expr[order(gene.expr$colors_curr, decreasing = TRUE),]
#   p1 <- ggscatter(gene.expr,x='delta',y='p.adj.log', size=0.5, color = "colors_curr", palette = c("#be1e2d","grey"),label=gene.expr$tf,repel = TRUE, font.label = c(7),label.select = gene.expr[gene.expr$tf %in% tf_markers[[i]],]$tf,xlab = gsub("_","/",names(tf_markers)[[i]]),show.legend.text=FALSE, ylab = FALSE) + geom_hline(yintercept=1.3, linetype="dashed", color = "black", size=0.3) + geom_vline(xintercept=0.5, linetype="dashed", color = "black", size=0.3) + geom_vline(xintercept=-0.5, linetype="dashed", color = "black", size=0.3) + theme_pubr(base_size = 6.5, base_family = "Helvetica") + theme(legend.position="none",axis.title.y=element_blank())
#   plot_list[[i]] <- p1
# }

plot_list <- list()
for (i in seq_along(tf_markers)){
  gene.expr <- read.csv(paste0("./220208/tf_activity/",names(tf_markers)[[i]],"_state_tfact_markers.csv"), row.names = 1)
  gene.expr$colors_curr <- rep("grey",dim(gene.expr)[1])
  gene.expr$tf <- toupper(unlist(lapply(rownames(gene.expr), function(x){str_split(x,"_")[[1]][1]})))
  gene.expr$colors_curr[gene.expr$tf %in% tf_markers[[i]]] <- "#be1e2d"
  gene.expr <- gene.expr[order(gene.expr$colors_curr, decreasing = TRUE),]
  
  
  #set labels
  lab_italics <- gene.expr$tf
  selectLab_italics = tf_markers[[i]]
  
  #set colors
  key2 <- gene.expr$colors_curr
  names(key2) <- gene.expr$colors_curr


  p1 <- EnhancedVolcano(gene.expr,
  lab = lab_italics,
  x = 'delta',
  y = 'p.adj',
  title = '',
  subtitle='',
  pCutoff = 0.05,
  selectLab = selectLab_italics,
  xlim = c(min(gene.expr$delta, na.rm = TRUE), max(gene.expr$delta, na.rm = TRUE)),
  ylim = c(min(-log10(gene.expr$p.adj), na.rm = TRUE)-0.1, max(-log10(gene.expr$p.adj), na.rm = TRUE)),
  parseLabels = TRUE,
  boxedLabels = TRUE,
  FCcutoff = 0.5,
  pointSize = 1,
  colAlpha = 1,
  labSize = 2,
  labFace = "bold",
  colCustom = key2,
  legendIconSize = 0,
  legendLabSize = 0,
  drawConnectors = TRUE,
  widthConnectors = 0.1,
  colConnectors = 'black',
  arrowheads = FALSE,
  gridlines.major = FALSE,
  gridlines.minor = FALSE,
  border = 'partial',
  borderWidth = 1,
  caption="",
  borderColour = 'black') + ggpubr::theme_pubr(base_size = 7) + ylab("") + xlab(gsub("_","/",names(tf_markers)[[i]])) + theme(legend.position = "none",
                                                                                                                                plot.margin = margin(0,0,0,0, "cm"))
  p1
  plot_list[[i]] <- p1
}

p3 <- ggarrange(plotlist = plot_list, nrow = 1)
ggsave(filename = "220208/tf_activity/tf_volcanoMerge2.pdf", plot = p3, width = 9, height = 2)


p2 <- ggarrange(plotlist = plot_list, nrow = 1)
ggsave(filename = "220208/tf_activity/tfact_volcanoMerge2.pdf", plot = p2, width = 6, height = 1.5)

# ggsave(filename = FILE_SAVE, plot = p1, width = 1.5, height = 1)

p2
```


#expression plotting
```{r}

mono.gene <- c("Ms4a3","Ifitm1","Spp1","Ctsg","Prtn3")
neutro.gene <- c("Ctsg","Elane","S100a8","S100a9")
em.gene <- c("Gata1","Gata2","Pf4","Hbb.bt")
lym.gene <- c("Flt3","Mef2c","Bcl11a","Ighm","Il12a")
dc.gene <-c("Cox6a2","Ighm","Ly6d","Cd74")
bem.gene <- c("Gata2","Cpa3","Cyp11a1","Mcpt8")

gene_markers <- list()
gene_markers[['Mono']] <- mono.gene
gene_markers[['Neutro']] <- neutro.gene
gene_markers[['Ery_Meg']] <- em.gene
gene_markers[['Lym']] <- lym.gene
gene_markers[['pDC_Ccr7DC']] <- dc.gene
gene_markers[['Baso_Eos_Mast']] <- bem.gene



plot_list <- list()
for (i in seq_along(gene_markers)){
  gene.expr <- read.csv(paste0("./220208/gene_expr/",names(gene_markers)[[i]],"_state_geneexpr_markers.csv"), row.names = 1)
  gene.expr$colors_curr <- rep("grey",dim(gene.expr)[1])
  gene.expr$colors_curr[rownames(gene.expr) %in% gene_markers[[i]]] <- "#0e4fad"
  gene.expr <- gene.expr[order(gene.expr$colors_curr, decreasing = TRUE),]
  
  #set labels
  lab_italics <- paste0("italic('", rownames(gene.expr), "')")
  selectLab_italics = paste0(
    "italic('",
    gene_markers[[i]],
    "')")
  
  #set colors
  key2 <- gene.expr$colors_curr
  names(key2) <- gene.expr$colors_curr


  p1 <- EnhancedVolcano(gene.expr,
  lab = lab_italics,
  x = 'delta',
  y = 'p.adj',
  title = '',
  subtitle='',
  pCutoff = 0.05,
  selectLab = selectLab_italics,
  xlim = c(min(gene.expr$delta, na.rm = TRUE), max(gene.expr$delta, na.rm = TRUE)),
  ylim = c(min(-log10(gene.expr$p.adj), na.rm = TRUE)-0.1, max(-log10(gene.expr$p.adj), na.rm = TRUE)),
  parseLabels = TRUE,
  boxedLabels = TRUE,
  FCcutoff = 0.5,
  pointSize = 1,
  colAlpha = 1,
  labSize = 2,
  labFace = "bold",
  colCustom = key2,
  legendIconSize = 0,
  legendLabSize = 0,
  drawConnectors = TRUE,
  widthConnectors = 0.1,
  colConnectors = 'black',
  arrowheads = FALSE,
  gridlines.major = FALSE,
  gridlines.minor = FALSE,
  border = 'partial',
  borderWidth = 1,
  caption="",
  borderColour = 'black') + ggpubr::theme_pubr(base_size = 7) + ylab("") + xlab(gsub("_","/",names(gene_markers)[[i]])) + theme(legend.position = "none",
                                                                                                                                plot.margin = margin(0,0,0,0, "cm"))
  p1
  plot_list[[i]] <- p1
}

p3 <- ggarrange(plotlist = plot_list, nrow = 1)
ggsave(filename = "220208/gene_expr/ge_volcanoMerge2.pdf", plot = p3, width = 9, height = 2)

```

